server:
  port: 8001
dubbo:
  scan:
    base-packages: com.lzh.jmeter.system.main.service # 接口扫描地址
  protocol:
    name: dubbo
    port: -1 # dubbo协议 端口随机
  registry:
    address: zookeeper://127.0.0.1:2181 # zookeeper连接地址
    timeout: 10000 # 超时时间
  metadata-report:
    address: zookeeper://127.0.0.1:2181 # 数据元中心

spring:
  application:
    name: jmeter-system
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/nethp-test?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/nethp-test?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0
        max-active: 8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 600MB
